SET hive.cli.print.header=true;
SELECT COUNT(DISTINCT(Unemployed_2016)) AS DistinctVal  FROM unemp_pov ;
SELECT MIN(Unemployed_2016) AS MinVal  FROM unemp_pov ;
SELECT MAX(Unemployed_2016) AS MaxVal  FROM unemp_pov ;
SELECT AVG(Unemployed_2016) AS AvgVal  FROM unemp_pov ;
SELECT Count(Unemployed_2016) AS Nullval  FROM unemp_pov WHERE Unemployed_2016 is null  ;
SELECT Count(Unemployed_2016) AS Missinval  FROM unemp_pov WHERE Unemployed_2016 Like''  ;
SELECT Unemployed_2016,(Unemployed_2016/S.Suma)*100 AS PercentVal FROM unemp_pov JOIN (SELECT SUM(Unemployed_2016) AS Suma FROM unemp_pov) AS S ORDER BY Unemployed_2016 DESC LIMIT 10;